//
// Created by anton on 7/30/22.
//

#ifndef KUMIR2_INSTRUCTIONS_H
#define KUMIR2_INSTRUCTIONS_H
namespace Arduino{
    static QString jsonInstructions = ""
                              "{\n"
                              "  \"instructions\":[\n"
                              "    {\n"
                              "      \"id\":1,\n"
                              "      \"value\":\"for \",\n"
                              "      \"name\":\"ForLoop\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":2,\n"
                              "      \"value\":\"while \",\n"
                              "      \"name\":\"WhileLoop\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":3,\n"
                              "      \"value\":\"do{\\n\",\n"
                              "      \"name\":\"DO\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":4,\n"
                              "      \"value\":\"\",\n"
                              "      \"name\":\"VAR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":5,\n"
                              "      \"value\":\"\",\n"
                              "      \"name\":\"ARR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":6,\n"
                              "      \"value\":\"\",\n"
                              "      \"name\":\"CONST\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":7,\n"
                              "      \"value\":\"\",\n"
                              "      \"name\":\"FUNC\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":8,\n"
                              "      \"value\":\"cin >> \",\n"
                              "      \"name\":\"INPUT\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":9,\n"
                              "      \"value\":\"cout << \",\n"
                              "      \"name\":\"OUTPUT\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":10,\n"
                              "      \"value\":\"\",\n"
                              "      \"name\":\"CALL\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":11,\n"
                              "      \"value\":\"return \",\n"
                              "      \"name\":\"RET\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":12,\n"
                              "      \"value\":\"\\n\\nERROR! \\n\\n\",\n"
                              "      \"name\":\"ERRORR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":13,\n"
                              "      \"value\":\"break;\",\n"
                              "      \"name\":\"BREAK\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":14,\n"
                              "      \"value\":\"if \",\n"
                              "      \"name\":\"IF\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":15,\n"
                              "      \"value\":\"else \",\n"
                              "      \"name\":\"ELSE\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":16,\n"
                              "      \"value\":\"\\n\",\n"
                              "      \"name\":\"STR_DELIM\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":17,\n"
                              "      \"value\":\", \",\n"
                              "      \"name\":\"END_ARG\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":18,\n"
                              "      \"value\":\"]\",\n"
                              "      \"name\":\"END_ARR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":19,\n"
                              "      \"value\":\"\\n}\",\n"
                              "      \"name\":\"END_ST\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":20,\n"
                              "      \"value\":\";\",\n"
                              "      \"name\":\"END_VAR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":21,\n"
                              "      \"value\":\")\\n{\\n\",\n"
                              "      \"name\":\"END_ST_HEAD\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":22,\n"
                              "      \"value\":\"(\",\n"
                              "      \"name\":\"START_SUB_EXPR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":23,\n"
                              "      \"value\":\")\",\n"
                              "      \"name\":\"END_SUB_EXPR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":24,\n"
                              "      \"value\":\" + \",\n"
                              "      \"name\":\"SUM\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":25,\n"
                              "      \"value\":\" - \",\n"
                              "      \"name\":\"SUB\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":26,\n"
                              "      \"value\":\" * \",\n"
                              "      \"name\":\"MUL\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":27,\n"
                              "      \"value\":\" / \",\n"
                              "      \"name\":\"DIV\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":28,\n"
                              "      \"value\":\"!\",\n"
                              "      \"name\":\"NEG\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":29,\n"
                              "      \"value\":\" && \",\n"
                              "      \"name\":\"AND\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":30,\n"
                              "      \"value\":\" || \",\n"
                              "      \"name\":\"OR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":31,\n"
                              "      \"value\":\" == \",\n"
                              "      \"name\":\"EQ\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":32,\n"
                              "      \"value\":\" != \",\n"
                              "      \"name\":\"NEQ\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":33,\n"
                              "      \"value\":\" < \",\n"
                              "      \"name\":\"LS\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":34,\n"
                              "      \"value\":\" > \",\n"
                              "      \"name\":\"GT\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":35,\n"
                              "      \"value\":\" <= \",\n"
                              "      \"name\":\"LEQ\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":36,\n"
                              "      \"value\":\" >= \",\n"
                              "      \"name\":\"GEQ\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":37,\n"
                              "      \"value\":\" = \",\n"
                              "      \"name\":\"ASG\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":38,\n"
                              "      \"value\":\"--\",\n"
                              "      \"name\":\"DCR\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":39,\n"
                              "      \"value\":\"++\",\n"
                              "      \"name\":\"INC\"\n"
                              "    },\n"
                              "    {\n"
                              "      \"id\":40,\n"
                              "      \"value\":\"\\n\\nbug\\n\\n\",\n"
                              "      \"name\":\"NOP\"\n"
                              "    }\n"
                              "  ]\n"
                              "}";
}
#endif //KUMIR2_INSTRUCTIONS_H
