void main() {
	тест(2);
	int ф;
	тест(тест1(1, тест4(4, 4, ф)));
}

тест(int а)
нач 
int аа = а - 1;
кон

int тест1(int б, int а)
нач 
int в = б - а;
return в;
кон

int тест4(int б, int а, int &р){
if (а >= 2 && б < 3) {
р = б - а;
}
else {
return ;
}
}

int тест5(int б, int а, int б1, float а2){
if(а >= 2 && б < 3 || б1 - б > 13 && а2 > 40){
тест(б);
}
else {
return;
}
}

int тест6(int &б, float а){
if(а >= 2 && б < 3){
б = тест5(4, 1, 2, 2);
}
else {
return;
}
}
