name: C/C++ CI

on:
  push:
    branches: [ "ArduinoFixes" ]
  pull_request:
    branches: [ "ArduinoFixes" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout tests branch
      uses: actions/checkout@v3
      with: 
        ref: translator_tests
    
    - name: test
      run: docker build -t ubuntu-test:latest - < arduino_test_dockerfile --build-arg path_to_tests_folder=./Tests
