name: C/C++ CI

on:
  push:
    branches: [ "ArduinoFixes" ]
  pull_request:
    branches: [ "ArduinoFixes" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: docker build < arduino_test_dockerfile 
